#!/usr/bin/env python3
"""Turn resume_data.json into the LaTeX files that Tectonic compiles.

This is the only pre-processor. The shell and PowerShell build scripts and the
GitHub Actions workflow all call it, so there is one implementation of the
escaping rules and one place a bug can live.

    python scripts/generate_latex.py            # write the LaTeX files
    python scripts/generate_latex.py --check    # report unfilled placeholders

Standard library only.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "resume" / "configuration"
SECTIONS = ROOT / "resume" / "sections"
SOURCE = ROOT / "resume" / "source"

DATA_FILE = CONFIG / "resume_data.json"
TEMPLATE_FILE = CONFIG / "resume_data.template.json"

PLACEHOLDER = re.compile(r"\[[A-Z0-9_]+\]")

# Every section the generator knows how to write, with its default heading.
# A section is emitted only when the JSON actually carries content for it, so
# a candidate with no publications simply has no Publications heading.
DEFAULT_TITLES = {
    "summary": "Summary",
    "experience": "Experience",
    "projects": "Projects",
    "skills": "Technical Skills",
    "education": "Education",
    "publications": "Publications",
    "certifications": "Certifications",
}

DEFAULT_ORDER = [
    "summary",
    "experience",
    "projects",
    "skills",
    "education",
    "publications",
    "certifications",
]

# A single-pass character map. Replacing character by character means a
# substitution can never be re-processed by a later rule, which is the failure
# that produced "$ $|$ $" in every pipe-separated field.
_ESCAPES = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
    "|": r"\textbar{}",
}


def tex(value) -> str:
    """Escape a value for LaTeX text mode."""
    if value is None:
        return ""
    return "".join(_ESCAPES.get(ch, ch) for ch in str(value))


def header(title: str) -> str:
    return (
        "%-------------------------------------------------------------------------\n"
        f"% {title}\n"
        "% Generated by scripts/generate_latex.py. Do not edit by hand.\n"
        "%-------------------------------------------------------------------------\n"
    )


def write(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body.rstrip() + "\n", encoding="utf-8")
    print(f"  wrote {path.relative_to(ROOT).as_posix()}")


# --------------------------------------------------------------------------
# Section writers. Each returns the LaTeX body, or None when there is nothing
# to say, in which case the section is left out of the document entirely.
# --------------------------------------------------------------------------

def sec_summary(data, title):
    text = (data.get("summary") or "").strip()
    if not text:
        return None
    return f"\\section{{{tex(title)}}}\n\\small {tex(text)}\n"


def sec_experience(data, title):
    roles = data.get("experience") or []
    if not roles:
        return None
    out = [f"\\section{{{tex(title)}}}", "\\begin{entries}"]
    for role in roles:
        out.append(
            "  \\entryTwoLine{%s}{%s}{%s}{%s}"
            % (tex(role.get("role")), tex(role.get("date")),
               tex(role.get("company")), tex(role.get("location")))
        )
        bullets = [b for b in (role.get("bullets") or []) if str(b).strip()]
        if bullets:
            out.append("  \\begin{bullets}")
            out += [f"    \\item \\small {tex(b)}" for b in bullets]
            out.append("  \\end{bullets}")
    out.append("\\end{entries}")
    return "\n".join(out) + "\n"


def sec_projects(data, title):
    projects = data.get("projects") or []
    if not projects:
        return None
    out = [f"\\section{{{tex(title)}}}", "\\begin{entries}"]
    for p in projects:
        name = tex(p.get("name"))
        stack = tex(p.get("stack"))
        left = f"\\textbf{{{name}}}" + (f" \\small \\textbar{{}} \\textit{{{stack}}}" if stack else "")
        url = (p.get("url") or "").strip()
        label = (p.get("url_label") or "").strip()
        if url:
            shown = tex(label or url)
            right = f"\\small \\href{{{url}}}{{{shown}}}"
        else:
            right = f"\\small {tex(p.get('date'))}"
        out.append(f"  \\entryOneLine{{{left}}}{{{right}}}")
        bullets = [b for b in (p.get("bullets") or []) if str(b).strip()]
        if bullets:
            out.append("  \\begin{bullets}")
            out += [f"    \\item \\small {tex(b)}" for b in bullets]
            out.append("  \\end{bullets}")
    out.append("\\end{entries}")
    return "\n".join(out) + "\n"


def sec_skills(data, title):
    return _labelled(data.get("skills"), title, "category", "items")


def sec_certifications(data, title):
    return _labelled(data.get("certifications"), title, "category", "items")


def _labelled(rows, title, key_field, value_field):
    rows = [r for r in (rows or []) if str(r.get(value_field, "")).strip()]
    if not rows:
        return None
    out = [f"\\section{{{tex(title)}}}", "\\begin{labelled}"]
    for row in rows:
        out.append(
            "  \\labelledLine{%s}{%s}"
            % (tex(str(row.get(key_field, "")).rstrip(":") + ":"),
               tex(row.get(value_field)))
        )
    out.append("\\end{labelled}")
    return "\n".join(out) + "\n"


def sec_education(data, title):
    schools = data.get("education") or []
    if not schools:
        return None
    out = [f"\\section{{{tex(title)}}}", "\\begin{entries}"]
    for s in schools:
        out.append(
            "  \\entryTwoLine{%s}{%s}{%s}{%s}"
            % (tex(s.get("institution")), tex(s.get("date")),
               tex(s.get("degree")), tex(s.get("location")))
        )
        detail = (s.get("detail") or "").strip()
        if detail:
            out.append("  \\begin{bullets}")
            out.append(f"    \\item \\small {tex(detail)}")
            out.append("  \\end{bullets}")
    out.append("\\end{entries}")
    return "\n".join(out) + "\n"


def sec_publications(data, title):
    pubs = data.get("publications") or []
    if not pubs:
        return None
    out = [f"\\section{{{tex(title)}}}", "\\begin{entries}"]
    for p in pubs:
        left = f"\\small {tex(p.get('citation'))}"
        url = (p.get("url") or "").strip()
        right = f"\\small \\href{{{url}}}{{{tex(p.get('url_label') or 'Link')}}}" if url else f"\\small {tex(p.get('date'))}"
        out.append(f"  \\entryOneLine{{{left}}}{{{right}}}")
    out.append("\\end{entries}")
    return "\n".join(out) + "\n"


WRITERS = {
    "summary": sec_summary,
    "experience": sec_experience,
    "projects": sec_projects,
    "skills": sec_skills,
    "education": sec_education,
    "publications": sec_publications,
    "certifications": sec_certifications,
}


# --------------------------------------------------------------------------

def build_metadata(info) -> str:
    """Contact details, the header lines, and the PDF metadata."""
    contact = [p for p in (info.get("phone"), info.get("email"), info.get("location"))
               if str(p or "").strip()]
    contact_line = " \\headerSep ".join(
        f"\\href{{mailto:{c}}}{{{tex(c)}}}" if "@" in str(c) else tex(c)
        for c in contact
    )

    links = [l for l in (info.get("links") or [])
             if str(l.get("url", "")).strip() and str(l.get("label", "")).strip()]
    link_line = " \\headerSep ".join(
        f"\\href{{{l['url']}}}{{{tex(l['label'])}}}" for l in links
    )

    lines = [
        header("Personal details, generated from resume_data.json"),
        f"\\newcommand{{\\myName}}{{{tex(info.get('name'))}}}",
    ]
    tagline = (info.get("title") or "").strip()
    if tagline:
        lines.append(f"\\newcommand{{\\myTagline}}{{{tex(tagline)}}}")
    lines += [
        f"\\newcommand{{\\myContactLine}}{{{contact_line}}}",
        f"\\newcommand{{\\myLinkLine}}{{{link_line}}}",
    ]
    return "\n".join(lines) + "\n"


def build_cover_letter(data, name_cmd="\\myName") -> str:
    cl = data.get("cover_letter") or {}
    rec = cl.get("recipient") or {}
    paragraphs = [p for p in (cl.get("paragraphs") or []) if str(p).strip()]
    greeting = (rec.get("greeting") or "").strip() or "Dear Hiring Team,"
    subject = (cl.get("subject") or "").strip()

    body = [
        header("Cover letter document"),
        "\\documentclass[letterpaper,11pt]{article}",
        "\\usepackage{../templates/cover_letter}",
        "\\input{../configuration/metadata}",
        f"\\setDocumentMetadata{{Cover Letter}}{{{tex(data['personal_info'].get('name'))}}}",
        "",
        "\\begin{document}",
        "",
        "\\makeHeader",
        "",
        "\\vspace{10pt}",
        "\\today",
        "",
        "\\letterRecipient{%s}{%s}{%s}" % (
            tex(rec.get("name")), tex(rec.get("company")), tex(rec.get("address"))),
        "",
    ]
    if subject:
        body += [f"\\textbf{{{tex(subject)}}}", ""]
    body += [f"{tex(greeting)}", ""]
    for para in paragraphs:
        body += [f"\\letterPara{{{tex(para)}}}", ""]
    body += [
        "\\vspace{6pt}",
        "Sincerely,",
        "",
        "\\vspace{18pt}",
        f"\\textbf{{{name_cmd}}}",
        "",
        "\\end{document}",
    ]
    return "\n".join(body) + "\n"


def check_placeholders(raw: str) -> list[str]:
    return sorted(set(PLACEHOLDER.findall(raw)))


def safe_name(data) -> str:
    """The filename stem for the built PDFs.

    Derived from the candidate's name, with anything that is awkward in a
    filename removed. While the name is still a placeholder the documents are
    published as plain 'Resume' and 'Cover_Letter' rather than advertising a
    release under a placeholder name.
    """
    name = str((data.get("personal_info") or {}).get("name", "")).strip()
    if not name or PLACEHOLDER.search(name):
        return ""
    cleaned = re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_")
    return cleaned


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="report unfilled placeholders and change nothing")
    ap.add_argument("--name", action="store_true",
                    help="print the filename stem for the built PDFs and exit")
    args = ap.parse_args()

    # Your own data wins. Without it the template is built, so a fresh clone
    # and the published release show the structure with its placeholders
    # visible, which is what a template should show.
    source = DATA_FILE if DATA_FILE.exists() else TEMPLATE_FILE
    if source is not DATA_FILE and not args.name:
        print(f"No {DATA_FILE.name}, building {source.name}.")

    raw = source.read_text(encoding="utf-8")
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as e:
        print(f"{source.name} is not valid JSON: {e}", file=sys.stderr)
        return 2

    if args.name:
        print(safe_name(data))
        return 0

    left = check_placeholders(raw)
    if args.check:
        if left:
            print(f"{len(left)} placeholder(s) still to fill:")
            for p in left:
                print("   ", p)
            return 1
        print("No placeholders left. The data file is fully populated.")
        return 0
    if left:
        print(f"Note: {len(left)} placeholder(s) still unfilled, "
              f"starting with {left[0]}.")

    info = data.get("personal_info") or {}
    resume = data.get("resume") or {}
    titles = {**DEFAULT_TITLES, **(resume.get("section_titles") or {})}
    order = resume.get("section_order") or DEFAULT_ORDER

    print("Generating LaTeX:")
    write(CONFIG / "metadata.tex", build_metadata(info))

    included = []
    for key in order:
        writer = WRITERS.get(key)
        if writer is None:
            print(f"  skipping unknown section '{key}'")
            continue
        body = writer(resume, titles.get(key, key.title()))
        if body is None:
            continue
        write(SECTIONS / f"{key}.tex", header(f"{titles.get(key, key)} section") + body)
        included.append(key)

    manifest = header("Section order, generated from resume_data.json") + "\n".join(
        f"\\input{{../sections/{k}}}" for k in included
    )
    write(SECTIONS / "_manifest.tex", manifest)

    write(SOURCE / "cover_letter.tex", build_cover_letter(data))

    print(f"Done. {len(included)} section(s): {', '.join(included)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
